apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: micropets-fish-python
  description: Micropets Fish Service
  tags:
    - python
    - flask
    - gunicorn
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name: fishes'
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
