apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSource
metadata:
  name: fishes-config
spec:
  backends:
  - type: git
    uri: https://github.com/bmoussaud/micropets-app-gitops
    defaultLabel: main
    searchPaths:
    - appconfig/micropets-dev/fishes-python
---
apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSlice
metadata:
  name: fishes-config
spec:
  interval: 1s
  configurationSource: fishes-config
  content:
  - application/default
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: fishes-config
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: fishes-config